"""Add missing columns to User table

Revision ID: 446f7f4d3c34
Revises: 
Create Date: 2024-12-25 13:41:56.318715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '446f7f4d3c34'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fname', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('lname', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('followers', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('followers_type', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('genre', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('gender', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('insta_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('yt_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('other_platform', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('age_group', sa.String(length=100), nullable=False))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('id')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('age_group')
        batch_op.drop_column('other_platform')
        batch_op.drop_column('country')
        batch_op.drop_column('yt_name')
        batch_op.drop_column('insta_name')
        batch_op.drop_column('gender')
        batch_op.drop_column('genre')
        batch_op.drop_column('followers_type')
        batch_op.drop_column('followers')
        batch_op.drop_column('lname')
        batch_op.drop_column('fname')

    op.create_table('users',
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('firstnane', sa.VARCHAR(length=200), nullable=False),
    sa.Column('lastnane', sa.VARCHAR(length=200), nullable=False),
    sa.Column('follow', sa.INTEGER(), nullable=False),
    sa.Column('typefollow', sa.VARCHAR(length=200), nullable=False),
    sa.Column('genre', sa.VARCHAR(length=200), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=False),
    sa.Column('instaname', sa.VARCHAR(length=200), nullable=False),
    sa.Column('otherplatform', sa.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###
